### ISSUE TITLE
Flex Pages: Context menu positioning

### ISSUE THREAD

**Issue by MarianArlt** [trilbymedia/grav-plugin-flex-objects#65]
I find that on v1.0.0-rc.12 the pages context menu has nothing to do with what I see in #20 
The button is positioned in between the page icon and the name of the page. This results in the context menu blocking the buttons further down the line:
![Screenshot_20200627_162851](https://user-images.githubusercontent.com/1492317/85932968-28a9a380-b897-11ea-9cac-d112700fe555.png)
It's bad UX, I would want to just click through all of them without having to close them. Now this could be simply remedied by pushing the popup to the right. But it's funny because as mentioned, in #20 it looks like this was very well thought out in the past having the buttons at the very right side, just the popup got positioned wrong. I came up with the same idea by myself, did a mockup and after that found the mentioned issue. Is this a regression or intended behavior?
![Screenshot_20200627_165052](https://user-images.githubusercontent.com/1492317/85932978-5a226f00-b897-11ea-83e0-1ab013bec439.png)
This is a fresh install with testing repo enabled and everything updated: Grav v1.7.0-rc.12 - Admin v1.10.0-rc.12

**Comment by w00fz** [comment]
This was intentional, reason for the change was to fix another ux issue where the contextual menu would overflow right to the next column like you have in the mock-up but then it would cause issues when you were three or more folders in. 
The menu would disappear on the far right and be hardly clickable.

That’s the main reason I had to change it, however I did prefer the original way as well.

**Comment by MarianArlt** [comment]
You mean the pop up leaving the viewport because you're in the right most directories?
From what I see in the inspector this is mostly controlled with Javascript, is it?
You could store half the width of the parent element that houses the columns, and in the eventListener for the button add a check for if the button is to the right of that half. If so, then put the popup x-axis on the left of the button instead of the right. Something along those lines:

    const parentWidth = document.querySelector('#layout-parent').offsetWidth,
             button           = document.querySelector('.layout-row .toggle-popup');
    button.addEventListener('click', function() {
        if (button.offsetLeft > (parentWidth / 2)) {
            // whatever logic to move popup to the left of button
        }
    });

Apparently I don't know your selectors, I tried to be as verbose as possible to illustrate the idea. Maybe I'm just being optimistic haha.

**Comment by w00fz** [comment]
That is somewhat similar to what I originally had but also was taking into account the scrolling position. However I soon realized that it’s a lot of computation for little benefit because after the first column you are almost every time going to end up with the menu having to open on the left to avoid overflowing. With the current approach it always open in the current column of interest.

The other things we weren’t happy about were:
1. The clash of count/arrow for going deeper and the dot dot dot menu wasn’t looking too great and was looking misaligned when you had pages and folders (pages don’t have count and arrow)
2. This shifting left and right caused the actions bar to look wrong. If you notice the delete is far away from the dot dot dot button and the closest action is the preview. This is on purpose so that it’s harder to accidentally click the delete. If we automatically switch the position of the menu left and right, now we also need to take care of switching that action bar too. It’s of course not such a complicated thing to do but as we were trying to keep things simple we compromised with this current disposition.

Now you have the whole picture, If you’d like to take a look at the commit history (https://github.com/trilbymedia/grav-plugin-flex-objects/commit/61bfd7b2ee3accee3761a1bf79dd987d2b0d36ff) for this and perhaps use the early version as a base for making some of the improvements discussed as PR, I’d be more than glad to review with the team and help with the code.

Clearly there’s different opinions on how this menu should be positioned and however I’m with you and believe the original version was better ux and ui wise, the reasons explained above and complexity that brought made us to implement the final version as it is. We did think it through both times. :)

**Comment by MarianArlt** [comment]
Thank you for the humble details. I doubt you're not thinking about UX. It's almost always a compromise. True. Maybe somebody comes along with the super genius idea but there's clearly more important things to work on anyways. (Myself included) Appreciate you taking your time for the insight here. Keep it coming! Great project!
